services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    volumes:
      - redis_volumn:/data

  api:
    container_name: api-service
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:3000
    depends_on:
      - redis
      - postgres
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - DATABASE_TYPE=postgres
      - DATABASE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres_password
      - JWT_SECRET=6e0e20af65f80d56b7a241b3cb264e97cc6bb944965b97995632ec444534ac60
      - JWT_ISSUER=http://localhost:3000
      - JWT_AUDIENCE=http://localhost
      - SERVER_DOMAIN=http://localhost:3000
      - SALT_ROUND=10
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USER=
      - REDIS_PASSWORD=

volumes:
  db_volume: {}
  redis_volumn: {}
